# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180220_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name2',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='lastname',
        ),
    ]
