# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180212_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my location deault', max_length=120),
        ),
    ]
