# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='description default text', null=True),
        ),
    ]
